// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AuditLog.Core.Models;

public partial class TransactionLog
{
    public string TableName { get; set; }

    public DateTime? ActionDateTime { get; set; }

    public string UserName { get; set; }

    public string OldValues { get; set; }

    public string NewValues { get; set; }

    public string TablePk { get; set; }

    public Guid Id { get; set; }

    public string Action { get; set; }
}